services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mood_diary_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["uvicorn", "mood_diary.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mood_diary_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    command: ["streamlit", "run", "mood_diary/frontend/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
