services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mood_diary_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["uvicorn", "mood_diary.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - db_data:/app
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mood_diary_frontend
    env_file:
      - .env
    command: ["streamlit", "run", "mood_diary/frontend/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  caddy:
    image: caddy:2-alpine
    container_name: mood_diary_caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend

volumes:
  caddy_data:
  caddy_config:
  db_data:
